### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by clintharris** [bnoordhuis/node-buffertools#18]
(Apologies if this is a dumb question.) When I installed on OSX I noticed that it compiled some C++ stuff... Assuming this means buffertools won't work on Windows?

**Comment by nalbion** [comment]
@bnoordhuis - I'm building a gulp plugin to process (edit) test scripts.  It scans through a file line by line and builds up a modified file (line by line).  For large files, would your still say that V8 would be just as efficient if were to append each line to an ever-growing string?

**Comment by bnoordhuis** [comment]
@nalbion Yes.  Alternatively, you can accumulate the strings in an array, then join them once you've read all lines.  Performance will be roughly on the same order as buffertools.concat() although memory usage may be a little higher if the strings contain non-ASCII.  There may also be some string encoding overhead.
