### ISSUE TITLE
Error by installation

### ISSUE THREAD

**Issue by Michael2222** [bnoordhuis/node-buffertools#60]
Greetings,
if I try to install the buffertools plugin, an error occured:

======================>>>
npm ERR! Failed at the buffertools@2.1.2 install script.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls buffertools
npm ERR! There is likely additional logging output above.
======================>>>

Can you help me?
Thank you!
   Michael

**Comment by zekylaf** [comment]
Hi, I have a problem with when I install buffertools in WIN SERVER 2012 r2. I can´t repair that. Can you help me please? Thanks!

This is the error:


C:\> npm install buffertools -g

> buffertools@2.1.2 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\buffertools
> node-gyp rebuild


C:\Users\Administrator\AppData\Roaming\npm\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
e_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Los proyectos de esta soluci¢n se van a compilar de uno en uno. Para habilitar la compilaci¢n en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVer
sion or PlatformToolset may be set to an invalid version number. [C:\Users\Administrator\AppData\Roaming\npm\node_modules\buffertools\build\buffertools.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(146,5): error MSB6006: "CL.exe" sali¢ con el c¢digo -1073741515. [C:\Users\Administrator
\AppData\Roaming\npm\node_modules\buffertools\build\buffertools.vcxproj]



npm : gyp ERR! build error 
En línea: 1 Carácter: 1
+ npm install buffertools -g
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (gyp ERR! build error :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
gyp
 
ERR!
 
stack
 Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp
 
ERR!
 
stack
     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp
 
ERR!
 
stack
     at ChildProcess.emit (events.js:110:17)
gyp
 
ERR!
 
stack
     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp
 
ERR!
 
System
 Windows_NT 6.3.9600
gyp
 
ERR!
 
command
 "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp
 
ERR!
 
cwd
 C:\Users\Administrator\AppData\Roaming\npm\node_modules\buffertools
gyp
 
ERR!
 
node -v
 v0.12.5
gyp
 
ERR!
 
node-gyp -v
 v2.0.1
gyp
 
ERR!
 
not ok
 
npm
 
ERR!
 Windows_NT 6.3.9600
npm
 
ERR!
 
argv
 "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "buffertools" "-g"
npm
 
ERR!
 
node
 v0.12.5
npm
 
ERR!
 
npm 
 v2.11.2
npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 buffertools@2.1.2 install: `node-gyp rebuild`
npm
 
ERR!
 Exit status 1
npm
 
ERR!
 
npm
 
ERR!
 Failed at the buffertools@2.1.2 install script 'node-gyp rebuild'.
npm
 
ERR!
 This is most likely a problem with the buffertools package,
npm
 
ERR!
 not with npm itself.
npm
 
ERR!
 Tell the author that this fails on your system:
npm
 
ERR!
     node-gyp rebuild
npm
 
ERR!
 You can get their info via:
npm
 
ERR!
     npm owner ls buffertools
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

**Comment by bnoordhuis** [comment]
@zekylaf You probably need to follow the steps described here: https://gist.github.com/kosmobot/6020327

**Comment by zekylaf** [comment]
Thanks you a lot!
