### ISSUE TITLE
io.js

### ISSUE THREAD

**Issue by Fishrock123** [bnoordhuis/node-buffertools#63]
@bnoordhuis Is this still supported? (or even needed?) Forrest's [deeper](https://github.com/othiym23/node-deeper) depends on this, which I had been using for some test stuffs.

If it is, how difficult would it be to Nan this for io.js?

**Comment by Fishrock123** [comment]
linking to iojs/io.js#456

**Comment by bnoordhuis** [comment]
Supported-ish but probably not needed.  What errors are you seeing?  I made it compatible with v0.11 in March last year (commit 559ca71) and a quick test suggests it works fine with io.js.

**Comment by Fishrock123** [comment]
My bad for not testing, I had assumed it probably didn't work. Sorry.
