### ISSUE TITLE
Node.js v0.12

### ISSUE THREAD

**Issue by SunilAgrawal** [bnoordhuis/node-buffertools#65]
Hi,

Is buffertools supported with Node.js v0.12. I am getting errors.

TIA.

**Comment by bnoordhuis** [comment]
It should work.  Can you be more specific?

**Comment by SunilAgrawal** [comment]
Sorry the issue was not in buffertools, rather npm. I read someone that
there's a bug in npm peer dependency check and the workaround was to
explicitly require 'requirejs' in package.json.

After I did that buffertools worked with Node 0.12.

**Comment by bnoordhuis** [comment]
Okay, thanks for your reply.  I'll close the issue.
