### ISSUE TITLE
npm install fails.

### ISSUE THREAD

**Issue by mattipr** [bnoordhuis/node-buffertools#66]
Hi,

When i try to do an npm install of this package on node v0.12.0, it fails with the following error.
Attached is the terminal screenshot with the details of the failure.
![console output](https://cloud.githubusercontent.com/assets/12124974/8587804/2eb3c86a-261f-11e5-94f3-12907bd722b2.png)

**Comment by bnoordhuis** [comment]
string.h is a standard header.  Do you have xcode installed?

**Comment by rails4sandeep** [comment]
OSX Yosemite Version 10.10.3

Installed whatever the app store shows the latest Developer Tools

I am getting this error

```ruby
npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
```

**Comment by bnoordhuis** [comment]
@rails4sandeep Can you file a new issue for that?  It unrelated to this issue.  Please include the contents of npm-debug.log.

I'm going to close this one because the OP never followed up.
