### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by 109km** [bnoordhuis/node-buffertools#72]
> buffertools@2.1.3 install /Users/xinhengs/Desktop/QunarDevs/qcms/node_modules/buffertools
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ETIMEDOUT
gyp ERR! stack     at exports._errnoException (util.js:860:11)
gyp ERR! stack     at TLSWrap.onread (net.js:544:26)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xinhengs/Desktop/QunarDevs/qcms/node_modules/buffertools
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "buffertools" "--unsafe-perm"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@2.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xinhengs/Desktop/QunarDevs/qcms/npm-debug.log

**Comment by bnoordhuis** [comment]
Not a buffertools issue.  That ETIMEDOUT error means node-gyp couldn't download the development headers from nodejs.org.
