### ISSUE TITLE
Unable to install the library on windows: Can't find Python executable "python"

### ISSUE THREAD

**Issue by vizmi** [bnoordhuis/node-buffertools#73]
I am unable to install the generator. Install fails with the following error message:

C:\Users...\AppData\Roaming\npm\node_modules\generator-redux\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"

As far as I understand PYTHON is not a usual requirement for javascript projects. Also it was not mentioned among  the project dependencies.

**Comment by vizmi** [comment]
Stuck with redux generator due to the same: https://github.com/banderson/generator-redux/issues/29

**Comment by bnoordhuis** [comment]
Python 2.7 is a requirement for [node-gyp](https://github.com/nodejs/node-gyp), the build tool for node.js addon-ons.  I'll close this because there is nothing node-buffertools can do here.
