### ISSUE TITLE
buffertools errors on npm install of passport-ldapbind

### ISSUE THREAD

**Issue by mem8754** [bnoordhuis/node-buffertools#74]
I am encountering the following errors when attempting an 'npm install passport-ldapbind':

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-                  gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mem/Projects/port/node_modules/buffertools
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
post@1.0.0 /Users/mem/Projects/port
└── (empty)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "passport-ldapbind"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mem/Projects/port/npm-debug.log
npm ERR! code 1

I can't tell if this is an issue with passport-ldapbind or with buffertools ...  npm-debug.log file attached:

[npm-debug.log.zip](https://github.com/bnoordhuis/node-buffertools/files/54738/npm-debug.log.zip)

Additional output from the npm install:

> buffertools@1.1.0 install /Users/mem/Projects/port/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
../buffertools.cc:19:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const Arguments& args, HandleScope& scope);
                                                          ^~~~~~~~~
                                                          v8::internal::Arguments
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:21:33: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> operator()(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:24:28: error: member access into incomplete type 'const v8::internal::Arguments'
                Local<Object> self = args.This();
                                         ^
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../buffertools.cc:26:55: error: no member named 'New' in 'v8::String'
                        return ThrowException(Exception::TypeError(String::New(
                                                                   ~~~~~~~~^
../buffertools.cc:35:86: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  ...apply(Handle<Object>& buffer, const uint8_t* data, size_t size, const Arguments& args, HandleScope& scope);
                                                                           ^~~~~~~~~
                                                                           v8::internal::Arguments
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:37:33: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> operator()(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:40:28: error: member access into incomplete type 'const v8::internal::Arguments'
                Local<Object> self = args.This();
                                         ^
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../buffertools.cc:42:55: error: no member named 'New' in 'v8::String'
                        return ThrowException(Exception::TypeError(String::New(
                                                                   ~~~~~~~~^
../buffertools.cc:46:11: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (args[0]->IsString()) {
                    ~~~~^~
../buffertools.cc:47:28: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        String::Utf8Value s(args[0]->ToString());
                                            ~~~~^~
../buffertools.cc:50:31: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (Buffer::HasInstance(args[0])) {
                                        ~~~~^~
../buffertools.cc:51:30: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        Local<Object> other = args[0]->ToObject();
                                              ~~~~^~
../buffertools.cc:56:88: error: no member named 'New' in 'v8::String'
                static Persistent<String> illegalArgumentException = Persistent<String>::New(String::New(
                                                                                             ~~~~~~~~^
../buffertools.cc:104:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const Arguments& args, HandleScope& scope) {
                                                          ^~~~~~~~~
                                                          v8::internal::Arguments
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:110:52: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
        Handle<Value> apply(Handle<Object>& buffer, const Arguments& args, HandleScope& scope) {
                                                          ^~~~~~~~~
                                                          v8::internal::Arguments
/Users/mem/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../buffertools.cc:111:11: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (args[0]->IsInt32()) {
                    ~~~~^~
../buffertools.cc:112:16: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        int c = args[0]->ToInt32()->Int32Value();
                                ~~~~^~
../buffertools.cc:116:11: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                if (args[0]->IsString()) {
                    ~~~~^~
../buffertools.cc:117:28: error: type 'const v8::internal::Arguments' does not provide a subscript operator
                        String::Utf8Value s(args[0]->ToString());
                                            ~~~~^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1

**Comment by bnoordhuis** [comment]
passport-ldapbind needs to update its dependencies, node-buffertools@1.1.0 is from June 2012.  The latest version is v2.1.3 and works fine with node.js v4.x.
