### ISSUE TITLE
node-gyp rebuild fail for hubot flowdock adapter on buffertools

### ISSUE THREAD

**Issue by littlebitplus** [bnoordhuis/node-buffertools#82]
Hello there, looking for any suggestions.  When installing the flowdock adapter for hubot, I receive:

This is on sles linux 12 box
[npm-debug.log.txt](https://github.com/bnoordhuis/node-buffertools/files/499011/npm-debug.log.txt)

virtual@cdlth002:~/timbot> bin/hubot -a flowdock

> buffertools@2.1.4 install /home/virtual/timbot/node_modules/buffertools
> node-gyp rebuild

make: Entering directory '/home/virtual/timbot/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
make: g++: Command not found
buffertools.target.mk:94: recipe for target 'Release/obj.target/buffertools/buffertools.o' failed
make: *** [Release/obj.target/buffertools/buffertools.o] Error 127
make: Leaving directory '/home/virtual/timbot/node_modules/buffertools/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.12.62-60.62-default
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/virtual/timbot/node_modules/buffertools
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Linux 3.12.62-60.62-default
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/virtual/timbot/npm-debug.log

Not sure where to look for additional feedback for the issue.  npm-debug.log is below:

**Comment by littlebitplus** [comment]
[npm-debug.log.txt](https://github.com/bnoordhuis/node-buffertools/files/499017/npm-debug.log.txt)

**Comment by bnoordhuis** [comment]
> make: g++: Command not found

You need to install a C++ compiler.

**Comment by littlebitplus** [comment]
I wondered about that, but:


virtual@cdlth002:~> sudo zypper install gcc
virtual's password:
Refreshing service 'spacewalk'.
Loading repository data...
Reading installed packages...
'gcc' is already installed.
No update candidate for 'gcc-4.8-6.189.x86_64'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.


And

virtual@cdlth002:~> zypper search gcc
Loading repository data...
Reading installed packages...

S | Name                        | Summary                                                   | Type
--+-----------------------------+-----------------------------------------------------------+--------
i | gcc                         | The system GNU C Compiler                                 | package
  | gcc-32bit                   | The system GNU C Compiler                                 | package
  | gcc-ada                     | The system GNU Ada Compiler                               | package
  | gcc-c++                     | The system GNU C++ Compiler                               | package
  | gcc-c++-32bit               | The system GNU C++ Compiler                               | package
  | gcc-fortran                 | The system GNU Fortran Compiler                           | package
  | gcc-gij                     | The system GNU Java bytecode interpreter                  | package
  | gcc-info                    | The system GNU Compiler documentation                     | package
  | gcc-java                    | The system GNU Java Compiler                              | package
  | gcc-locale                  | The system GNU Compiler locale files                      | package
  | gcc-obj-c++                 | The system GNU Objective C++ Compiler                     | package
  | gcc-objc                    | The system GNU Objective C Compiler                       | package
  | gcc-objc-32bit              | The system GNU Objective C Compiler                       | package
i | gcc48                       | The GNU C Compiler and Support Files                      | package
  | gcc48-32bit                 | The GNU C Compiler 32bit support                          | package
  | gcc48-ada                   | GNU Ada95 Compiler Based on GCC (GNAT)                    | package
  | gcc48-c++                   | The GNU C++ Compiler                                      | package
  | gcc48-fortran               | The GNU Fortran Compiler and Support Files                | package
  | gcc48-gij                   | Java Bytecode Interpreter for gcc                         | package
  | gcc48-info                  | Documentation for the GNU compiler collection             | package
  | gcc48-java                  | The GNU Java Compiler                                     | package
  | gcc48-locale                | Locale Data for the GNU Compiler Collection               | package
  | gcc48-obj-c++               | GNU Objective C++ Compiler                                | package
  | gcc48-objc                  | GNU Objective C Compiler                                  | package
  | gcc48-objc-32bit            | GNU Objective C Compiler                                  | package
  | gcc5                        | The GNU C Compiler and Support Files                      | package
  | gcc5                        | GCC 5 Compiler                                            | pattern
  | gcc5-32bit                  | The GNU C Compiler 32bit support                          | package
  | gcc5-ada                    | GNU Ada95 Compiler Based on GCC (GNAT)                    | package
  | gcc5-ada-32bit              | GNU Ada95 Compiler Based on GCC (GNAT)                    | package
  | gcc5-c++                    | The GNU C++ Compiler                                      | package
  | gcc5-c++-32bit              | The GNU C++ Compiler                                      | package
  | gcc5-fortran                | The GNU Fortran Compiler and Support Files                | package
  | gcc5-fortran-32bit          | The GNU Fortran Compiler and Support Files                | package
  | gcc5-info                   | Documentation for the GNU compiler collection             | package
  | gcc5-locale                 | Locale Data for the GNU Compiler Collection               | package
  | gcc6                        | The GNU C Compiler and Support Files                      | package
  | gcc6-32bit                  | The GNU C Compiler 32bit support                          | package
  | gcc6-ada                    | GNU Ada95 Compiler Based on GCC (GNAT)                    | package
  | gcc6-ada-32bit              | GNU Ada95 Compiler Based on GCC (GNAT)                    | package
  | gcc6-c++                    | The GNU C++ Compiler                                      | package
  | gcc6-c++-32bit              | The GNU C++ Compiler                                      | package
  | gcc6-fortran                | The GNU Fortran Compiler and Support Files                | package
  | gcc6-fortran-32bit          | The GNU Fortran Compiler and Support Files                | package
  | gcc6-info                   | Documentation for the GNU compiler collection             | package
  | gcc6-locale                 | Locale Data for the GNU Compiler Collection               | package
i | gccmakedep                  | Utility to list the resource database of an X application | package
  | libffi-devel-gcc5           | Foreign Function Interface library development files      | package
  | libffi-devel-gcc5-32bit     | Foreign Function Interface library development files      | package
i | libgcc_s1                   | C compiler runtime library                                | package
i | libgcc_s1-32bit             | C compiler runtime library                                | package
  | libstdc++6-devel-gcc5       | Include Files and Libraries mandatory for Development     | package
  | libstdc++6-devel-gcc5-32bit | Include Files and Libraries mandatory for Development     | package
  | libstdc++6-devel-gcc6       | Include Files and Libraries mandatory for Development     | package
  | libstdc++6-devel-gcc6-32bit | Include Files and Libraries mandatory for Development     | package
  | patterns-toolchain-gcc5     | GCC 5 Compiler                                            | package



as well, as part of the flowdock adapter, it requires redis, which is downloaded and a make run against it, which was successful.


So I thought I had the complier installed.

**Comment by littlebitplus** [comment]
As well, 

virtual@cdlth002:~> zypper search g++
Loading repository data...
Reading installed packages...

S | Name              | Summary                                      | Type
--+-------------------+----------------------------------------------+--------
  | libconfig++-devel | C++-Bindings development files for libconfig | package
  | libconfig++9      | Shared libraries for libconfig               | package

Am I wrong in thinking it's there?

**Comment by bnoordhuis** [comment]
Try installing gcc-c++; gcc is just the C compiler.

**Comment by littlebitplus** [comment]
Thanks.  I thought I had c/c++, but obviously I didn't.  

sudo zypper in gcc-c++

working now...
