### ISSUE TITLE
build is error?

### ISSUE THREAD

**Issue by Einsy** [bnoordhuis/node-buffertools#84]
C:\Users\Administrator
λ cd C:\nodejs\node-buffertools

C:\nodejs\node-buffertools
λ node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\nodejs\\node-buffertools\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\6.9.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\6.9.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\nodejs\\node-buffertools',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\nodejs\\node-buffertools\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok

C:\nodejs\node-buffertools
λ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.4 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  buffertools.cc
c:\nodejs\node-buffertools\BoyerMoore.h(35): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据 [C:\nodejs\node-buffertools\build\buffertools.v
cxproj]
c:\nodejs\node-buffertools\BoyerMoore.h(57): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据 [C:\nodejs\node-buffertools\build\buffertools.v
cxproj]
c:\nodejs\node-buffertools\BoyerMoore.h(61): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据 [C:\nodejs\node-buffertools\build\bu
ffertools.vcx
proj]
c:\nodejs\node-buffertools\BoyerMoore.h(62): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据 [C:\nodejs\node-buffertools\build\bu
ffertools.vcx
proj]
c:\nodejs\node-buffertools\BoyerMoore.h(110): warning C4267: “=”: 从“size_t”转换到“int”，可能丢失数据 [C:\nodejs\node-buffertools\build\buffertools.
vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(345): error C2988: 不可识别的模板声明/定义 [C:\nodejs\node-buffertools\build\buffertools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(345): error C2059: 语法错误:“using” [C:\nodejs\node-buffertools\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(481): error C2988: 不可识别的模板声明/定义 [C:\nodejs\node-buffertools\build\buffertools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(481): error C2059: 语法错误:“using” [C:\nodejs\node-buffertools\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(592): error C2061: 语法错误: 标识符“WeakCallbackType” [C:\nodejs\node-buffertools\build\buf
fertoo
ls.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(672): 参见对正在编译的类 模板 实例化“v8::PersistentBase<T>”的引用
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(667): error C2253: “PersistentBase<T>”: 纯说明符或抽象重写说明符只允许在虚函数上使用 [C:\no
dejs\node-buffertools
\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(874): error C2253: “Global<T>”: 纯说明符或抽象重写说明符只允许在虚函数上使用 [C:\nodejs\nod
e-buffertools\build\b
uffertools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(877): 参见对正在编译的类 模板 实例化“v8::Global<T>”的引用
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(882): error C2988: 不可识别的模板声明/定义 [C:\nodejs\node-buffertools\build\buffertools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(882): error C2059: 语法错误:“using” [C:\nodejs\node-buffertools\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(945): error C2989: “v8::HandleScope”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertoo
ls\build\bu
ffertools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(328) : 参见“v8::HandleScope”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(979): error C2989: “v8::EscapableHandleScope”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-
buffertools
\build\buffertools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(139) : 参见“v8::EscapableHandleScope”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(1009): error C2989: “v8::Data”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\bui
ld\bufferto
ols.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(76) : 参见“v8::Data”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(1143): error C2989: “v8::Script”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\b
uild\buffer
tools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(99) : 参见“v8::Script”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(1582): error C2989: “v8::StackTrace”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertoo
ls\build\bu
ffertools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(104) : 参见“v8::StackTrace”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(1645): error C2989: “v8::StackFrame”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertoo
ls\build\bu
ffertools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(103) : 参见“v8::StackFrame”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2060): error C2989: “v8::Value”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\bu
ild\buffert
ools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(112) : 参见“v8::Value”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2066): error C2989: “v8::Primitive”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertool
s\build\buf
fertools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(95) : 参见“v8::Primitive”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2081): error C2989: “v8::Boolean”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\
build\buffe
rtools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(72) : 参见“v8::Boolean”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2101): error C2989: “v8::Name”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\bui
ld\bufferto
ols.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(88) : 参见“v8::Name”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2469): error C2989: “v8::String”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\b
uild\buffer
tools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(105) : 参见“v8::String”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2508): error C2989: “v8::Symbol”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\b
uild\buffer
tools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(107) : 参见“v8::Symbol”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2536): error C2989: “v8::Private”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\
build\buffe
rtools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(109) : 参见“v8::Private”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2550): error C2989: “v8::Number”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\b
uild\buffer
tools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(89) : 参见“v8::Number”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2565): error C2989: “v8::Integer”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\
build\buffe
rtools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(84) : 参见“v8::Integer”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2579): error C2989: “v8::Int32”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\bu
ild\buffert
ools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(83) : 参见“v8::Int32”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(2593): error C2989: “v8::Uint32”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\b
uild\buffer
tools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(110) : 参见“v8::Uint32”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3015): error C2989: “v8::Object”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\b
uild\buffer
tools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(91) : 参见“v8::Object”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3045): error C2989: “v8::Array”: 类 模板 已经声明为非类 模板 [C:\nodejs\node-buffertools\bu
ild\buffert
ools.vcxproj]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(71) : 参见“v8::Array”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3249): error C2504: “v8::Object”: 未定义基类 [C:\nodejs\node-buffertools\build\buffertools.
vcxp
roj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3256): error C2061: 语法错误: 标识符“FunctionCallback” [C:\nodejs\node-buffertools\build\bu
fferto
ols.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3260): error C2061: 语法错误: 标识符“FunctionCallback” [C:\nodejs\node-buffertools\build\bu
fferto
ols.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3263): error C2535: “v8::MaybeLocal<F> v8::Function::New(v8::Local<T>)”: 已经定义或声明成员
函数 [C:\n
odejs\node-buffertools\build\buffertools.vcxproj]
          with
          [
              F=v8::Function,
              T=v8::Context
          ]
          c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3255) : 参见“v8::Function::New”的声明
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3267): error C2061: 语法错误: 标识符“FunctionCallback” [C:\nodejs\node-buffertools\build\bu
fferto
ols.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3277): error C2059: 语法错误:“return” [C:\nodejs\node-buffertools\build\buffertools.vcxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3277): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3282): error C2146: 语法错误: 缺少“;”(在标识符“Call”的前面) [C:\nodejs\node-buffertools\bui
ld\buffertoo
ls.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3288): error C2270: “GetName”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools\build\b
uffertools.
vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3296): error C2270: “GetInferredName”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools
\build\buff
ertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3302): error C2270: “GetDebugName”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools\bu
ild\buffert
ools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3308): error C2270: “GetDisplayName”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools\
build\buffe
rtools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3314): error C2270: “GetScriptLineNumber”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffert
ools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3319): error C2270: “GetScriptColumnNumber”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffe
rtools\buil
d\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3324): error C2270: “IsBuiltin”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools\build
\buffertool
s.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3329): error C2270: “ScriptId”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools\build\
buffertools
.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3335): error C2270: “GetBoundFunction”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertool
s\build\buf
fertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3337): error C2270: “GetScriptOrigin”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools
\build\buff
ertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3341): error C2059: 语法错误:“private” [C:\nodejs\node-buffertools\build\buffertools.vcxpro
j]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3342): error C2059: 语法错误:“)” [C:\nodejs\node-buffertools\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3351): error C2504: “Object”: 未定义基类 [C:\nodejs\node-buffertools\build\buffertools.vcxp
roj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3353): error C2504: “Object”: 未定义基类 [C:\nodejs\node-buffertools\build\buffertools.vcxp
roj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3359): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3359): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3359): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3360): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3360): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3361): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3366): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3366): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3366): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3372): error C2061: 语法错误: 标识符“Local” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3374): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3374): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3374): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3376): error C2061: 语法错误: 标识符“Local” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3378): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3378): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3378): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3380): error C2061: 语法错误: 标识符“Value” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3384): error C2061: 语法错误: 标识符“Value” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3394): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3394): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3394): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3397): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3397): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3397): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3400): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3400): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3400): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3401): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3401): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3402): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3405): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3405): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3405): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3406): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3406): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3407): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3415): error C2061: 语法错误: 标识符“Value” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3419): error C2061: 语法错误: 标识符“Value” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3427): error C2504: “Object”: 未定义基类 [C:\nodejs\node-buffertools\build\buffertools.vcxp
roj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3429): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3429): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3429): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3430): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3430): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3430): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3437): error C2143: 语法错误 : 缺少“;”(在“<”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3437): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3439): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3441): error C2061: 语法错误: 标识符“Value” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3445): error C2061: 语法错误: 标识符“Value” [C:\nodejs\node-buffertools\build\buffertools.v
cxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3462): error C2504: “Object”: 未定义基类 [C:\nodejs\node-buffertools\build\buffertools.vcxp
roj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3479): error C2628: “ArrayBuffer::Allocator”后面接“void”是非法的(是否忘记了“;”?) [C:\nodejs
\node-buffe
rtools\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3505): error C3861: “data_”: 找不到标识符 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3505): error C2461: “Contents”: 构造函数语法缺少形参 [C:\nodejs\node-buffertools\build\buff
ertools.v
cxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3505): error C2059: 语法错误:“常量” [C:\nodejs\node-buffertools\build\buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3505): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3505): error C2143: 语法错误 : 缺少“;”(在“{”的前面) [C:\nodejs\node-buffertools\build\buffe
rtools.vc
xproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3505): error C2334: “{”的前面有意外标记；跳过明显的函数体 [C:\nodejs\node-buffertools\build
\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3507): error C2059: 语法错误:“return” [C:\nodejs\node-buffertools\build\buffertools.vcxproj
]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3507): error C2238: 意外的标记位于“;”之前 [C:\nodejs\node-buffertools\build\buffertools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3508): error C2146: 语法错误: 缺少“;”(在标识符“ByteLength”的前面) [C:\nodejs\node-buffertoo
ls\build\buf
fertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3508): error C2270: “ByteLength”: 非成员函数上不允许修饰符 [C:\nodejs\node-buffertools\buil
d\buffertoo
ls.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3508): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int [C:\nodejs\node-b
uffertools\build\
buffertools.vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3508): error C2065: “byte_length_”: 未声明的标识符 [C:\nodejs\node-buffertools\build\buffer
tools.
vcxproj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3510): error C2059: 语法错误:“private” [C:\nodejs\node-buffertools\build\buffertools.vcxpro
j]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3514): error C2255: “friend”: 不允许位于类定义之外 [C:\nodejs\node-buffertools\build\buffer
tools.vcx
proj]
c:\users\administrator\.node-gyp\6.9.4\include\node\v8.h(3514): fatal error C1003: 错误计数超过 100；正在停止编译 [C:\nodejs\node-buffertools\build\
buffertools.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\nodejs\node-buffertools
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

C:\nodejs\node-buffertools
λ

**Comment by Einsy** [comment]
win7
 x64
 node6.9.4 
vs2012

**Comment by bnoordhuis** [comment]
Upgrade your compiler.  VS 2015 works, 2012 does not.
