### ISSUE TITLE
build questions

### ISSUE THREAD

**Issue by Einsy** [bnoordhuis/node-buffertools#87]
1、win10, x64   node6.9.4/node.0.12.5/node4.3.3   vs2015 build ok;

2  win8.1 x64 node6.9.4 vs2015 build error;

3  win7  x64 node6.9.4 vs2015 build error;

**Comment by Einsy** [comment]
This is a error on win8.1 vs2015 x64 node6.9.4

G:\nodejs>npm install buffertools

> buffertools@2.1.4 install G:\nodejs\node_modules\buffertools
> node-gyp rebuild


G:\nodejs\node_modules\buffertools>if not defined npm_config_node_gyp (node "D:\
Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  buffertools.cc
  win_delay_load_hook.cc
g:\nodejs\node_modules\buffertools\BoyerMoore.h(35): warning C4267: “=”: 从“s
ize
_t”转换到“int”，可能丢失数据 (..\buffertools.cc) [G:\nodejs\node_modules\buff
ertools\buil
d\buffertools.vcxproj]
g:\nodejs\node_modules\buffertools\BoyerMoore.h(57): warning C4267: “=”: 从“s
ize
_t”转换到“int”，可能丢失数据 (..\buffertools.cc) [G:\nodejs\node_modules\buff
ertools\buil
d\buffertools.vcxproj]
g:\nodejs\node_modules\buffertools\BoyerMoore.h(61): warning C4267: “初始化”:
从“si
ze_t”转换到“const int”，可能丢失数据 (..\buffertools.cc) [G:\nodejs\node_modu
les\bufferto
ols\build\buffertools.vcxproj]
g:\nodejs\node_modules\buffertools\BoyerMoore.h(62): warning C4267: “初始化”:
从“si
ze_t”转换到“const int”，可能丢失数据 (..\buffertools.cc) [G:\nodejs\node_modu
les\bufferto
ols\build\buffertools.vcxproj]
g:\nodejs\node_modules\buffertools\BoyerMoore.h(110): warning C4267: “=”: 从“
siz
e_t”转换到“int”，可能丢失数据 (..\buffertools.cc) [G:\nodejs\node_modules\buf
fertools\bui
ld\buffertools.vcxproj]
..\buffertools.cc(219): warning C4267: “初始化”: 从“size_t”转换到“const int
”，可能丢失数据 [G
:\nodejs\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(220): warning C4267: “初始化”: 从“size_t”转换到“const int
”，可能丢失数据 [G
:\nodejs\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(332): warning C4267: “=”: 从“size_t”转换到“int32_t”，可
能丢失数据 [G:\no
dejs\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(334): warning C4267: “=”: 从“size_t”转换到“int32_t”，可
能丢失数据 [G:\no
dejs\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(340): warning C4244: “参数”: 从“const ptrdiff_t”转换到“in
t32_t”，可能丢
失数据 [G:\nodejs\node_modules\buffertools\build\buffertools.vcxproj]
..\buffertools.cc(419): warning C4267: “参数”: 从“size_t”转换到“int”，可能
丢失数据 [G:\nodej
s\node_modules\buffertools\build\buffertools.vcxproj]
C:\Users\Administrator\.node-gyp\6.9.4\Release\node.lib : fatal error LNK1106:
文件无效或磁盘已满:  无法查找到 0x645B0 [G:\nodejs\node_modules\buffertools\buil
d\buffertools
.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\nodejs\node_modules\buffertools
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'G:\nodejs\package.json'

npm WARN nodejs No description
npm WARN nodejs No repository field.
npm WARN nodejs No README data
npm WARN nodejs No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "buffertools"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buffertools
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\nodejs\npm-debug.log

G:\nodejs>

**Comment by bnoordhuis** [comment]
Can you stop filing new issues all the time and stick to #86?  For that particular linker error, see https://msdn.microsoft.com/en-us/library/dxd2zbyd.aspx.
