### ISSUE TITLE
buffertools.node not found

### ISSUE THREAD

**Issue by FarihaAbbasi1123** [bnoordhuis/node-buffertools#91]
I'm trying to run gulp build command and when I run that I get the following error:

D:\imodeljstest\test-imodel-service>gulp build
D:\imodeljstest\test-imodel-service\node_modules\buffertools\buffertools.js:26
        if (e.code !== 'MODULE_NOT_FOUND') throw e;
                                           ^

Error: The specified module could not be found.
\\?\D:\imodeljstest\test-imodel-service\node_modules\buffertools\build\Release\buffertools.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\imodeljstest\test-imodel-service\node_modules\buffertools\buffertools.js:24:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

P.S: i'm using 64 bit operating system and node.js version is 8.2.1 and architecture is 64bit.

**Comment by bnoordhuis** [comment]
What do D:\imodeljstest\test-imodel-service\node_modules\buffertools\build and D:\imodeljstest\test-imodel-service\node_modules\buffertools\build\Release contain?

**Comment by FarihaAbbasi1123** [comment]
It actually contain many files including buffertools.node.

The path from which it is requesting a file is actually there.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bnoordhuis** [comment]
Can you try upgrading node.js to v8.7.0?  It's possible you're hitting a bug that's been fixed.  This path in particular - `\?\D:\imodeljstest\test-imodel-service\...` - looks suspect, I think it should have two leading backslashes.

That said, the error message could also mean that buffertools.node is compiled for the wrong architecture.  Check what `node -p process.arch` prints and pass that to npm / node-gyp with the `--arch=...` parameter.

**Comment by FarihaAbbasi1123** [comment]
Following are the results of executing the commands. Please update

D:\imodeljstest\test-imodel-service>node -p process.arch
x64

D:\imodeljstest\test-imodel-service>npm/node-gyp --arch=x64

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s, se,
    search, set, shrinkwrap, star, stars, start, stop, t, team,
    test, tst, un, uninstall, unpublish, unstar, up, update, v,
    version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Fariha.Abbasi\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.3.0 C:\Program Files\nodejs\node_modules\npm

**Comment by bnoordhuis** [comment]
npm/node-gyp means npm OR node-gyp, i.e., `npm install --arch=x64` or `node-gyp rebuild --arch=x64`.

**Comment by FarihaAbbasi1123** [comment]
Thanks its working now.

**Comment by bnoordhuis** [comment]
Happy to hear that.
